#!/usr/bin/python3
"""Module that factorizes as many numbers as possible
into a product of two smaller numbers."""
from sys import argv

def factorize(value):
    """Print a simple decomposition of an integer > 1"""
    i = 2

    if value < 2:
        return
    print("{:.0f}={:.0f}*{:.0f}".format(value, value / i, i))

if len(argv) != 2:
    print("Usage: {} <file>".format(argv[0]))
    exit(1)

try:
    with open(argv[1]) as file:
        line = file.readline()

        while line != "":
            value = int(line.strip())
            factorize(value)
            line = file.readline()

except FileNotFoundError:
    print("Error: File not found")
except Exception as e:
    print("An error occurred:", e)
