#!/usr/bin/env python3
import sys
import subprocess
import time

def check_factor(args):
    if len(args) != 3:
        num2 = 1
        for a in args[2:]:
            num2 *= int(a)
    else:
        num2 = int(args[2])

    num1 = int(args[1])
    num = args[0].replace(':', '=')

    if num2 > num1:
        num1, num2 = num2, num1

    print(f"{num}{num1}*{num2}")

def timeout_command(file_path):
    with open(file_path, 'r') as file:
        for line in file:
            result = subprocess.run(['factor', line.strip()], capture_output=True, text=True)
            check_factor(result.stdout.split()[1:])

if len(sys.argv) != 2:
    print('Usage: factors.py <file>')
    sys.exit(1)

start_time = time.time()
timeout_command(sys.argv[1])
end_time = time.time()
runtime = end_time - start_time

print(f"Total runtime: {runtime:.3f} seconds")
